services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./sagrada-familia/milagres:/www
   - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
  - php
 php:
  image: php:7.4-fpm
  container_name: php-fpm
  volumes:
  - ./sagrada-familia/milagres:/www
